[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
# Use Solidity 0.8.20 with Paris EVM version for PulseChain compatibility
optimizer = true
optimizer_runs = 200
auto_detect_solc = false
solc_version = "0.8.20"
# Use Paris EVM version for PulseChain compatibility (no MCOPY opcode)
evm_version = "paris"
# Ignore old PulseX contracts with incompatible Solidity versions
ignored_error_codes = [5574]
ignore = [
    "src/pulsex/PulseXFactory.sol",
    "src/pulsex/PulseXRouter02.sol", 
    "src/pulsex/WPLS.sol",
    "script/DeployPulseXTestnet.s.sol"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
